server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservations/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka